### ISSUE TITLE
code is injected to each layer twice

### ISSUE THREAD

**Issue by ZiqianXie** [jonasz/progressive_infogan#2]
In your code, the `infogan_vars` are injected twice at each block, once to the `prev_net` ant once to the `net`, what's the purpose of this double injection or did I miss anything?

**Comment by jonasz** [comment]
Hi ZiqianXie. Injecting the code into multiple activation layers within a single block is intentional. That approach is inspired by the WaveNet paper, where multiple activations within the network are conditioned. Let me know if that answers your question.

**Comment by ZiqianXie** [comment]
I see, thank you for the answer!
